### PR TITLE
Add option to right justify tags 

### PR DESCRIPTION
**Pull request by connormclaud**
Discussion https://github.com/minad/org-modern/discussions/207

image

Known issues:
1. Removes org-habit's future dates graphs

### CODE REVIEW

**Comment by connormclaud** [comment]
@minad PTAL

**Comment by connormclaud** [comment]
@minad Just a friendly reminder that my PR is awaiting your review

**Comment by minad** [comment]
@connormclaud Please be patient.

**Comment by minad** [comment]
Hi, I finally took a look at your PR. I think it is too complicated - too much code, only to support right tag alignment. I experimented with a simpler method in https://github.com/minad/org-modern/commit/148f6c4159fa6f480fc9556ae1f6080957fdc968, deleting some space in front of the tags. But unfortunately this will also lead to misalignment, if we don't measure the actual width of the tags. You use string-pixel-width for this purpose, but this function is unfortunately not supported on older Emacs versions. Also measuring pixel size like this is quite costly. I am afraid, we are not going to support right alignment of tags for the time being. The README of org-modern recommends to set the tag column to 0 for this reason.

**Pull request closed without merging**
