### PR TITLE
Tec blocks

### PR DESCRIPTION
**Pull request by minad**
@tecosaur recreated here

### CODE REVIEW

**Comment by minad** [comment]
Unfortunately there is a regression. If you use the default settings and start with emacs -Q, then the result will look differently for blocks which are indented.

~~~ 
#+begin_src elisp
  ...
#+end_src

versus

  #+begin_src elisp
    ...
  #+end_src
~~~

**Comment by tecosaur** [comment]
1. Thanks :slightly_smiling_face: 
2. Gah! I thought I had it sorted this time

**Comment by tecosaur** [comment]
@minad can I confirm that the 'regression' you see is that source blocks are now indented like text, whereas before they were kept right against the left margin?

I put quotes around 'regression' because trying this out I'm not sure if the original behaviour is actually desirable. This is what I see.

**`main`**

image

**`tec-blocks`**

image

For comparison, without org-modern I see this:

image

What are your thoughts?

**Comment by minad** [comment]
> can I confirm that the 'regression' you see is that source blocks are now indented like text, whereas before they were kept flush against the left margin?

Yes, they are supposed to be flushed to the left. I like this behavior and I consider changing it a regression.

However the problems with these fringe blocks is that they only look nice if you use frame borders and window dividers to create some space. There is also @jdtsmith's [org-modern-indent](https://github.com/jdtsmith/org-modern-indent). Unfortunately this package has other flaws. Still, we should be looking for a solution for the blocks which works better in more scenarios.

The advantage of your PR is that it decouples the fringe and block name settings. So it is a step in the right direction.

**Comment by tecosaur** [comment]
Ok, I now understand that you see this as a negative change, not just different.

While I like the idea of the fringes, in practice they're not quite what I'd hope for. I do admire your perseverance in avoiding overlays though.

Moving forwards, if this is the only remaining issue, I think I know how it can be handled (or turned into yet-another-option, but I'm aware you try not to go overboard with those :stuck_out_tongue:).

**Comment by minad** [comment]
> While I like the idea of the fringes, in practice they're not quite what I'd hope for. I do admire your perseverance in avoiding overlays though.

Yes, fringes are not great and also not great for this purpose. Overall these different border types don't look like a coherent design (margins, fringes, line number display, line prefix, ...). Emacs suffers from (mis)feature accumulation, but Emacs is only Emacs because of that.

> Moving forwards, if this is the only remaining issue, I think I know how it can be handled (or turned into yet-another-option, but I'm aware you try not to go overboard with those stuck_out_tongue).

I think you should simply check org-modern-block-fringe in the the block name replacement. If fringe non-nil then the name should be flushed, otherwise it shouldn't.

**Comment by tecosaur** [comment]
> I think you should simply check org-modern-block-fringe in the the block name replacement. If fringe non-nil then the name should be flushed, otherwise it shouldn't.

Implemented. I can't push to the branch, so here's a patch:

[0001-Hide-some-block-indentation-if-fringe-is-enabled.txt](https://github.com/minad/org-modern/files/9252733/0001-Hide-some-block-indentation-if-fringe-is-enabled.txt)

(Apparently, GitHub doesn't let you upload `.patch` files :roll_eyes:, so I changed the extension to `.txt`)

**Comment by tecosaur** [comment]
Oh, there might be a misplaced paren pair. If so, try this:
```diff
@@ -626,8 +626,8 @@ (define-minor-mode org-modern-mode
-                    (((and (consp org-modern-block-name) ; static replacement
-                           (stringp (car org-modern-block-name)))
-                      `((,@block-indent?
-                         (2 '(face nil display ,(car org-modern-block-name)))
-                         ,block-append) .
-                         (,@block-indent?
-                          (2 '(face nil display ,(cadr org-modern-block-name)))
-                          ,block-append))))
+                    ((and (consp org-modern-block-name) ; static replacement
+                          (stringp (car org-modern-block-name)))
+                     `((,@block-indent?
+                        (2 '(face nil display ,(car org-modern-block-name)))
+                        ,block-append) .
+                        (,@block-indent?
+                         (2 '(face nil display ,(cadr org-modern-block-name)))
+                         ,block-append)))
```

**Comment by tecosaur** [comment]
Hi Daniel, might you have had a chance to test this out yet?

**Comment by minad** [comment]
No, I don't have much time to spare right now unfortunately.

**Comment by tecosaur** [comment]
Righteo, I'll look forward to hearing from you when things have calmed down a bit for you then :+1:.

**Comment by minad** [comment]
Can you please bring this PR in a form which I can test/merge directly?

**Comment by tecosaur** [comment]
Sure, I'll make a new PR shortly. Not to tempt fate, but I *think* everything works now, if not at least I won't be sharing `.patch` files in comments :laughing:.

**Pull request closed without merging**
