### PR TITLE
Add custom style to inner links

### PR DESCRIPTION
**Pull request by roygbyte**
This is my first time writing with eLisp, so feel free to question anything I've done. There may be a better way... 

Speaking of which... there is a little bug in my code that I can't figure out for the life of me. It has to do with the `defcustom` for `org-modern-internal-link-text`. I can't get the values to correspond with the logic of the states. For whatever reason, it's backwards. Try it... you'll see what I mean...

### CODE REVIEW

**Comment by minad** [comment]
Thank you for your contribution! This looks good. A few things to consider: I am currently debating if it makes sense to apply such heavy styling to dates, because they look compressed. Instead one could apply the tag-styling only to elements which appear in headlines. If date styling is removed, then adding internal link target styling wouldn't be in order. However since everything is configurable we have some freedom. What do you think?

**Comment by roygbyte** [comment]
Well, I guess my thoughts are fairly simple. Give the plugin some default styling and just let the user ultimately decide how they want the modifications to work. 

This PR only targets the internal link anchor, and not the link itself, btw.

**Comment by minad** [comment]
Okay, I agree with you. I am happy to add this! 

There is a small complication though - I am distributing (or planning to distribute) most of my packages via GNU ELPA which requires copyright assignment to the FSF for changes larger than 15 lines of code. For this package this would then allow the Org maintainers to take code from here and potentially add it to Org itself, since the package would then fall under the same copyright terms as Org itself. On the other hand, the package may be too trivial/uninteresting for the Org people to consider.

I am sorry to bother with this in particular since this is your first time contributing Elisp. The assignment process is described here https://protesilaos.com/emacs/modus-themes#h:111773e2-f26f-4b68-8c4f-9794ca6b9633 for example. Is it possible for you and are you willing to go through with the assignment? On the plus side this allows you to also contribute non-trivial code to Emacs itself. Please let me know your thoughts! :)

**Comment by roygbyte** [comment]
You should checkout this PR first and see about the bug I'm referring to. It's probably a simple fix for the stalwarts of Elisp. Just wouldn't want a silly little thing to make it into your crisp new package...

Yes, I'd have no problem assigning over my infinitesimal contribution :) Happy to join the "bazaar"... and yes... it may open the path to more contributions to Emacs itself... you just let me know when I should go ahead and do that.

**Comment by minad** [comment]
No worries about the bug! We will figure this out in due time.

> Yes, I'd have no problem assigning over my infinitesimal contribution :) Happy to join the "bazaar"... and yes... it may open the path to more contributions to Emacs itself... anyways, you just let me know when I should go ahead and do that.

Sounds good! Then I propose you follow the steps described in https://protesilaos.com/emacs/modus-themes#h:111773e2-f26f-4b68-8c4f-9794ca6b9633. You fill out this form, send it to the FSF via email and then you will get another form to sign to finish the process. This shouldn't take much longer than two weeks. Please ping me as soon the assignment is completed.

**Comment by roygbyte** [comment]
@minad Have not heard back yet from FSF. Is that normal?

**Comment by minad** [comment]
Yes. Sometimes they are a bit slow.

**Comment by roygbyte** [comment]
@minad I am all squared up!

**Comment by minad** [comment]
@roygbyte Sorry for letting this sit for so long. I will take a closer look soon!

**Comment by minad** [comment]
Hey @roygbyte, I reworked and simplified your PR slightly. Please take a look if it works for you. I hope I didn't miss anything!

**Comment by roygbyte** [comment]
@minad I'll have to trust your judgement here. My Elisp ability has progressed a little bit since this PR (I'm about halfway through the "Lisp: A Gentle Introduction to Symbolic Computation"), but not enough to reason about what you've changed. In any case... thanks for including my PR!

**Comment by minad** [comment]
The main change was that I remove the custom fontification function. I moved all the "logic" to the font lock keywords. You don't have to check the code, but please take a look if it works for you!

**Comment by roygbyte** [comment]
When an internal link is inserted as `<<some-link>>` it is properly styled.
When an internal link is inserted as `<<some-link>> Some text` is it not properly styled--the last two characters of the link (`>>`) remain visible, when instead they should be removed.

**Comment by minad** [comment]
Fixed in https://github.com/minad/org-modern/commit/136d29b1a0bcb268607f293d6e5c1f78210300ba

**Comment by roygbyte** [comment]
Also seems that when invoking `M-x customize-variable org-modern-internal-link` the function returns `Symbol’s function definition is void: nil`. 

I think it should be:

``` elisp
(defcustom org-modern-internal-link '(" ↪ " t " ")
  "Prettify internal links, e.g., <<introduction>>."
  :type '(choice (list string boolean string)))
```

instead of 

``` elisp
(defcustom org-modern-internal-link '(" ↪ " t " ")
  "Prettify internal links, e.g., <<introduction>>."
  :type '(choice nil (list string boolean string)))
```

**Pull request merged**
